### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by tremulaes** [mattbaker/ruby-heap-viz#1]
Please add Ubuntu support. 

> > viz!
> > Couldn't get a file descriptor referring to the console
> > false

![image](https://cloud.githubusercontent.com/assets/8475694/6394103/364b5e66-bd9d-11e4-8e4a-2ac2c232a55c.png)

**Comment by mattbaker** [comment]
What happens if you just open `viz.html` manually?

**Comment by mattbaker** [comment]
@secade — bump. need more context or I'll be closing this.

99% there is an `open` command in Linux that's unrelated. `viz!` could do OS detection (a PR would be welcome) to handle this. But, again, I'd like you to try it and investigate.
